tools:
    external_code_coverage: true

filter:
    paths:
        - "Command/*"
        - "DependencyInjection/*"
        - "*.php"
    excluded_paths:
        - "Resources/*"
        - "Tests/*"

checks:
    php:
        duplication: false


build:
    tests:
        override:
            -
                command: SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT=1 ./vendor/bin/simple-phpunit --coverage-clover build/logs/clover.xml ./test
                coverage:
                    file: build/logs/clover.xml
                    format: clover
