filter:
    paths:
        - "Command/*"
        - "DependencyInjection/*"
        - "*.php"
    excluded_paths:
        - "Resources/*"
        - "Tests/*"

checks:
    php:
        duplication: false

build:
    dependencies:
        before:
            - pecl install pcov
        after:
            - composer require eventsauce/message-repository-for-doctrine
    tests:
        override:
            -
                command: ./vendor/bin/phpunit --coverage-clover target/coverage.xml
                coverage:
                    file:   target/coverage.xml
                    format: clover
