os:
    - linux

language: php

cache:
    directories:
        - $HOME/.cache/composer
        - $HOME/.composer/cache
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

env:
    global:
        - PHPUNIT_FLAGS="-v"
        - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

matrix:
    allow_failures:
        - php: 7.2snapshot
        - php: 7.3snapshot
        - php: 7.4snapshot
        - php: master
    fast_finish: true
    include:
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="max[self]=0"
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-stable" SYMFONY_DEPRECATIONS_HELPER="max[self]=0"
        - php: 7.4
          env: COMPOSER_FLAGS="--prefer-stable" SYMFONY_DEPRECATIONS_HELPER="max[self]=0"

        - php: 7.2
        - php: 7.3
          env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"
        - php: 7.4

        - php: 7.2
          env: DEPENDENCIES="symfony/lts:^4" STABILITY="dev"
        - php: 7.3
          env: DEPENDENCIES="symfony/lts:^4" STABILITY="dev"
        - php: 7.4
          env: DEPENDENCIES="symfony/lts:^4" STABILITY="dev"

        - php: 7.2snapshot
        - php: 7.3snapshot
        - php: 7.4snapshot

        - stage: "PHP 8.0"
          php: master

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
    - if [ -n "$GH_AUTHTOKEN" ]; then composer config github-oauth.github.com ${GH_AUTHTOKEN}; fi;
    - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - ./vendor/bin/simple-phpunit install

script:
    - composer validate --strict --no-check-lock
    - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS
