language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"
        - php: 7.3
          env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"
        - php: 7.2
          env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"
        - php: 7.3
          env: DEPENDENCIES="symfony/lts:^3"
        - php: 7.2
          env: DEPENDENCIES="symfony/lts:^3"
        - php: 7.3
          env: STABILITY="dev"
        - php: 7.2
          env: STABILITY="dev"
    allow_failures:
        - env: STABILITY="dev"

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
    - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - composer require phpunit/phpunit

script:
    - ./vendor/bin/phpunit
